=== cisene/swish-123/xml/swish-123-datasource.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entries"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="entries">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="organization" minOccurs="1"/>
        <xs:element ref="categories" minOccurs="0"/>
        <xs:element name="web" minOccurs="1" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="number" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="organization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" minOccurs="1" type="xs:string"/>
        <xs:element name="number" minOccurs="1" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="category" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="category">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== cisene/swish-123/xml-data/swish-123-datasource.xml
<?xml version="1.1" encoding="UTF-8"?>
<root xmlns:xs="http://www.w3.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="./swish-123-datasource.xsd">
  <entries>
    <entry number="1230712752">
      <organization>
        <name>Teskedsorden</name>
        <number/>
      </organization>
      <web>https://teskedsorden.se/</web>
    </entry>

    <entry number="1236071302">
      <organization>
        <name>Save the Orangutan</name>
        <number/>
      </organization>
      <web>http://savetheorangutan.se/</web>
    </entry>

    <entry number="1239000068">
      <organization>
        <name>Personskadeförbundet RTP</name>
        <number/>
      </organization>
      <web>https://rtp.se/</web>
    </entry>

    <entry number="1239000209">
      <organization>
        <name>Clowner utan Gränser</name>
        <number/>
      </organization>
      <web>https://www.skratt.nu/</web>
    </entry>

    <entry number="1239000316">
      <organization>
        <name>Kristna Fredsrörelsen</name>
        <number/>
      </organization>
      <web>https://www.krf.se</web>
    </entry>

    <entry number="1239000506">
      <organization>
        <name>PMU</name>
        <number/>
      </organization>
      <web>https://pmu.se/</web>
    </entry>

    <entry number="1239000548">
      <organization>
        <name>Ersta Diakoni</name>
        <number/>
      </organization>
      <web>http://www.erstadiakoni.se/</web>
    </entry>

    <entry number="1239000597">
      <organization>
        <name>Barndiabetesfonden</name>
        <number/>
      </organization>
      <web/>
    </entry>

    <entry number="1239000670">
      <organization>
        <name>Insamlingsstiftelsen Akademiska sjukhusets barnfond</name>
        <number>802424-9289</number>
      </organization>
      <categories>
        <category type="insamling"/>
        <category type="välgörenhet"/>
        <category type="insamlingskontroll"/>
      </categories>
      <web>https://akademiskasbarnfond.se/</web>
    </entry>

    <entry number="1239001090">
      <organization>
        <name>Läkare i Världen</name>
        <number/>
      </organization>
      <web>https://www.lakareivarlden.se/</web>
    </entry>

    <entry number="1239001298">
      <organization>
        <name>Civil Rights Defenders</name>
        <number/>
      </organization>
      <web>https://crd.org/sv/</web>
    </entry>

    <entry number="1239001561">
      <organization>
        <name>Sällsynta Diagnoser</name>
        <number/>
      </organization>
      <web>https://www.sallsyntadiagnoser.se</web>
    </entry>

    <entry number="1239001629">
      <organization>
        <name>Insamlingsstiftelsen WaterAid Sverige</name>
        <number/>
      </organization>
      <web>https://www.wateraid.org/se/</web>
    </entry>

    <entry number="1239001702">
      <organization>
        <name>Göteborgs Stadsmission</name>
        <number/>
      </organization>
      <web>https://www.stadsmissionen.org</web>
    </entry>

    <entry number="1239001744">
      <organization>
        <name>World Animal Protection Sverige</name>
        <number/>
      </organization>
      <web>https://www.worldanimalprotection.se/</web>
    </entry>

    <entry number="1239001819">
      <organization>
        <name>Islamic Relief</name>
        <number/>
      </organization>
      <web>https://islamic-relief.se/</web>
    </entry>

    <entry number="1239002171">
      <organization>
        <name>ALEF, Adult Learning and Empowerment Faciliators</name>
        <number>802452-4681</number>
      </organization>
      <categories>
        <category type="insamling"/>
        <category type="välgörenhet"/>
        <category type="insamlingskontroll"/>
      </categories>
      <web>https://www.alef.org/</web>
    </entry>

    <entry number="1239002189">
      <organization>
        <name>Framtidsjorden</name>
        <number/>
      </organization>
      <web>https://www.framtidsjorden.se</web>
    </entry>

    <entry number="1239002262">
      <organization>
        <name>Svenska Livräddningssällskapet</name>
        <number/>
      </organization>
      <web>https://svenskalivraddningssallskapet.se/</web>
    </entry>

    <entry number="1239002296">
      <organization>
        <name>SOS Barnbyar</name>
        <number/>
      </organization>
      <web>http://www.sosbarnbyar.se/</web>
    </entry>

    <entry number="1239002320">
      <organization>
        <name>Involvaid</name>
        <number/>
      </organization>
      <web>https://involvaid.com/</web>
    </entry>

    <entry number="1239002437">
      <organization>
        <name>Yennenga Progress</name>
        <number/>
      </organization>
      <web>https://www.yennengaprogress.se/</web>
    </entry>

    <entry number="1239002494">
      <organization>
        <name>Right Livelihood-stiftelsen</name>
        <number/>
      </organization>
      <web>https://rightlivelihoodaward.org/</web>
    </entry>

    <entry number="1239002536">
      <organization>
        <name>Hoppets stjärna</name>
        <number/>
      </organization>
      <web>https://www.starofhope.se/</web>
    </entry>

    <entry number="1239003377">
      <organization>
        <name>Afrikagrupperna</name>
        <number>802007-2446</number>
      </organization>
      <categories>
        <category type="insamling"/>
        <category type="välgörenhet"/>
        <category type="insamlingskontroll"/>
      </categories>
      <web>https://afrikagrupperna.se/</web>
    </entry>

    <entry number="1239003419">
      <organization>
        <name>Sam-Hjälp</name>
        <number/>
      </organization>
      <web>http://www.samhjalp.se/</web>
    </entry>

    <entry number="1239003443">
      <organization>
        <name>Brottsofferjouren</name>
        <number/>
      </organization>
      <web>https://www.brottsofferjouren.se/</web>
    </entry>

    <entry number="1239003609">
      <organization>
        <name>Cancer- och Allergifonden</name>
        <number/>
      </organization>
      <web>https://www.cancerochallergifonden.se/</web>
    </entry>

    <entry number="1239003666">
      <organization>
        <name>Insamlingsstiftelsen till minne av Gustav Whitefield</name>
        <number/>
      </organization>
      <web>https://www.gustavwhitefield.com/</web>
    </entry>

    <entry number="1239003674">
      <organization>
        <name>Njurfonden</name>
        <number/>
      </organization>
      <web>https://www.njurfonden.se/</web>
    </entry>

    <entry number="1239003831">
      <organization>
        <name>Insamlingsstiftelsen Skiers Left – Mikaelas minne</name>
        <number/>
      </organization>
      <web>https://www.skiersleft.com/</web>
    </entry>

    <entry number="1239004011">
      <organization>
        <name>Insamlingsstiftelsen Gatubarn</name>
        <number/>
      </organization>
      <web>https://www.stiftelsengatubarn.se/</web>
    </entry>

    <entry number="1239004375">
      <organization>
        <name>Cancerhjälpen</name>
        <number/>
      </organization>
      <web>https://www.cancerhjalpen.se/</web>
    </entry>

    <entry number="1239004441">
      <organization>
        <name>Räddningsmissionen</name>
        <number/>
      </organization>
      <web>https://raddningsmissionen.se/</web>
    </entry>

    <entry number="1239004540">
      <organization>
        <name>Human Rights Watch</name>
        <number/>
      </organization>
      <web>http://www.hrw.se</web>
    </entry>

    <entry number="1239004656">
      <organization>
        <name>Help Kurdistan insamlingsstiftelse</name>
        <number/>
      </organization>
      <web>http://www.helpkurdistan.se/</web>
    </entry>

    <entry number="1239004805">
      <organization>
        <name>Frälsningsarmén</name>
        <number/>
      </organization>
      <web>https://www.fralsningsarmen.se/</web>
    </entry>

    <entry number="1239004870">
      <organization>
        <name>Jontefonden</name>
        <number/>
      </organization>
      <web>https://www.jontefonden.se/</web>
    </entry>

    <entry number="1239005000">
      <organization>
        <name>Sjöräddningssällskapet</name>
        <number/>
      </organization>
      <web>https://www.sjoraddning.se/</web>
    </entry>

    <entry number="1239005083">
      <organization>
        <name>Vi-skogen</name>
        <number/>
      </organization>
      <web>https://www.viskogen.se/</web>
    </entry>

    <entry number="1239005133">
      <organization>
        <name>Min Stora Dag</name>
        <number/>
      </organization>
      <web>https://www.minstoradag.org/</web>
    </entry>

    <entry number="1239005547">
      <organization>
        <name>War Child</name>
        <number/>
      </organization>
      <web>https://www.warchild.se/</web>
    </entry>

    <entry number="1239005604">
      <organization>
        <name>Stiftelsen Sällsyntafonden</name>
        <number>802479-8202</number>
      </organization>
      <categories>
        <category type="insamling"/>
        <category type="välgörenhet"/>
        <category type="insamlingskontroll"/>
      </categories>
      <web>https://www.agrenska.se/sallsyntafonden/</web>
    </entry>

    <entry number="1239005745">
      <organization>
        <name>Ung Cancer</name>
        <number/>
      </organization>
      <web>https://ungcancer.se/</web>
    </entry>

    <entry number="1239005802">
      <organization>
        <name>Unite 2 Learn</name>
        <number/>
      </organization>
      <web>http://www.unite2learn.org/</web>
    </entry>

    <entry number="1239005877">
      <organization>
        <name>Hjärtebarnsfonden</name>
        <number/>
      </organization>
      <web>http://www.hjartebarnsfonden.se/</web>
    </entry>

    <entry number="1239005919">
      <organization>
        <name>Bröstcancerförbundet</name>
        <number/>
      </organization>
